export const PROJECTS = [
  {
    id: "gcp-foundation",
    title: "GCP Foundation",
    description:
      "My first serious project — reusable Terraform modules for GCP infrastructure. After months of Cloud Skills Boost labs, I wanted to consolidate everything into a real, production-like template I could build on.",
    role: [
      "Designed modular structure: separate modules for VPC, GKE, Cloud SQL, IAM, Cloud NAT",
      "VPC module: custom network with private subnets, secondary IP ranges for GKE pods and services",
      "GKE module: regional cluster with separate node pool, Workload Identity, private cluster configuration with Cloud NAT",
      "Cloud SQL module: PostgreSQL 15 with private IP (VPC peering), automated backups, maintenance window",
      "IAM module: dedicated service accounts with minimal permissions, Workload Identity binding for GKE pods",
      "Configured remote state: GCS backend with state locking and versioning",
      "CI/CD: GitHub Actions pipeline — terraform fmt, validate, plan on PR; apply on merge to main",
      "Environment separation: dev/staging via Terraform workspaces with different variable files",
    ],
    learned: "Terraform best practices: module composition, state management, DRY configurations. Deep understanding of GCP networking model and IAM hierarchy. This project taught me to think in infrastructure — not just run commands, but design systems.",
    techStack: [
      "Terraform",
      "GCP",
      "GKE",
      "Cloud SQL",
      "VPC",
      "GitHub Actions",
    ],
    category: "Cloud",
    imgPath: "",
    ghLink: "https://github.com/meisnastia/gcp-foundation",
    demoLink: "",
  },
  {
    id: "statushive",
    title: "StatusHive",
    description:
      "After building infrastructure, I realized: you can't manage what you can't observe. Built a complete observability stack from scratch to understand monitoring fundamentals — from metric collection to alerting.",
    role: [
      "Composed Docker stack with 5 services: Prometheus, Grafana, Loki, Alertmanager, Promtail",
      "Prometheus: scrape configs for node-exporter, cAdvisor, and a custom Go app with /metrics endpoint",
      "Grafana: pre-provisioned dashboards via JSON files — system metrics, container stats, log viewer",
      "Loki + Promtail: log collection from all Docker containers with label-based filtering",
      "Alertmanager: alert rules for high CPU (>80%), low disk space, container restart loops → Telegram bot notifications",
      "Added sample Go application with custom Prometheus metrics (request_count, response_latency_seconds) for testing the full pipeline",
      "Wrote README with setup instructions and architecture diagram",
    ],
    learned: "Full observability pipeline: metrics collection → visualization → alerting. PromQL basics, Grafana dashboard design, log aggregation patterns. Key insight: monitoring isn't just dashboards — it's about defining what 'healthy' means for your system.",
    techStack: [
      "Docker Compose",
      "Prometheus",
      "Grafana",
      "Loki",
      "Alertmanager",
      "Go",
    ],
    category: "Monitoring",
    imgPath: "",
    ghLink: "https://github.com/meisnastia/statushive",
    demoLink: "",
  },
  {
    id: "vertex-rag-infra",
    title: "Vertex RAG Platform",
    description:
      "My most complex project — production-grade DevOps infrastructure for a RAG (Retrieval-Augmented Generation) AI pipeline on GCP. Worked under mentorship: the senior engineer designed the ML architecture, I owned the entire infrastructure layer.",
    role: [
      "Created GCP project structure with Terraform: enabled APIs, service accounts, IAM bindings with least-privilege",
      "Provisioned networking: VPC with private subnet, Cloud NAT for egress, firewall rules for internal communication",
      "Set up AlloyDB instance with pgvector extension for vector embeddings storage (private IP, VPC peering)",
      "Configured Cloud Run deployment for the RAG API service: Dockerfile review, environment variables, scaling policy",
      "Created Vertex AI endpoint configuration for the embedding model (text-embedding-004)",
      "Built GitHub Actions CI/CD: Terraform lint → plan → apply (manual approval), Docker build → push to Artifact Registry → deploy to Cloud Run",
      "Configured Cloud Monitoring dashboards: request latency, error rate, token usage metrics",
      "Set up alerting: Slack notifications when error rate exceeds SLO threshold",
    ],
    learned: "How AI infrastructure differs from regular web apps: GPU resource planning, embedding latency optimization, vector search tuning, cost management for AI workloads. Also learned to work in a team — code reviews, architecture discussions, incident response.",
    techStack: [
      "GCP",
      "Vertex AI",
      "Cloud Run",
      "AlloyDB",
      "Terraform",
      "GitHub Actions",
      "Docker",
      "Cloud Monitoring",
    ],
    category: "AI/MLOps",
    imgPath: "",
    ghLink: "https://github.com/meisnastia/vertex-rag-infra",
    demoLink: "",
  },
  {
    id: "hiveops",
    title: "HiveOps",
    description:
      "This portfolio itself — built and deployed using the same DevOps practices I apply to infrastructure projects. Full GitOps workflow: code in GitHub, CI/CD pipeline, automated deployment. Because a DevOps engineer's portfolio should be a DevOps project.",
    role: [
      "Designed and built the site: React + Vite, responsive Liquid Glass design, i18n (EN/UA)",
      "Set up GitHub repository with branch protection rules and PR-based workflow",
      "Created GitHub Actions CI/CD: lint → build → deploy on merge to main",
      "Infrastructure as Code: deployment configuration managed in Git",
      "PDF resume generation with @react-pdf/renderer (build-time, not client-side)",
      "Interactive terminal resume — because engineers read terminals, not PDFs",
      "Monitoring: uptime checks, performance budgets, Lighthouse CI",
    ],
    learned: "End-to-end project ownership: from design to deployment to monitoring. Applying DevOps culture to everything — even a personal website deserves proper CI/CD and observability.",
    techStack: [
      "React",
      "Vite",
      "GitHub Actions",
      "Git",
      "Node.js",
      "i18n",
    ],
    category: "Platform",
    imgPath: "",
    ghLink: "https://github.com/meisnastia/hiveops",
    demoLink: "https://smartbee.me",
  },
];

export const PROJECT_CATEGORIES = ["All", "Cloud", "Monitoring", "AI/MLOps", "Platform"];
