export const PROJECTS = [
  {
    id: "gcp-foundation",
    title: "GCP Foundation",
    description:
      "My first serious project — reusable Terraform modules for GCP infrastructure. After months of Cloud Skills Boost labs, I wanted to consolidate everything into a real, production-like template I could build on.",
    role: [
      "Designed modular structure: separate modules for VPC, GKE, Cloud SQL, IAM, Cloud NAT",
      "VPC module: custom network with private subnets, secondary IP ranges for GKE pods and services",
      "GKE module: regional cluster with separate node pool, Workload Identity, private cluster configuration with Cloud NAT",
      "Cloud SQL module: PostgreSQL 15 with private IP (VPC peering), automated backups, maintenance window",
      "IAM module: dedicated service accounts with minimal permissions, Workload Identity binding for GKE pods",
      "Configured remote state: GCS backend with state locking and versioning",
      "CI/CD: GitHub Actions pipeline — terraform fmt, validate, plan on PR; apply on merge to main",
      "Environment separation: dev/staging via Terraform workspaces with different variable files",
    ],
    learned: "Terraform best practices: module composition, state management, DRY configurations. Deep understanding of GCP networking model and IAM hierarchy. This project taught me to think in infrastructure — not just run commands, but design systems.",
    techStack: [
      "Terraform",
      "GCP",
      "GKE",
      "Cloud SQL",
      "VPC",
      "GitHub Actions",
    ],
    category: "Cloud",
    imgPath: "",
    ghLink: "",
    demoLink: "",
  },
  {
    id: "statushive",
    title: "StatusHive",
    description:
      "After building infrastructure, I realized: you can't manage what you can't observe. Built a complete observability stack from scratch to understand monitoring fundamentals — from metric collection to alerting.",
    role: [
      "Composed Docker stack with 5 services: Prometheus, Grafana, Loki, Alertmanager, Promtail",
      "Prometheus: scrape configs for node-exporter, cAdvisor, and a custom Go app with /metrics endpoint",
      "Grafana: pre-provisioned dashboards via JSON files — system metrics, container stats, log viewer",
      "Loki + Promtail: log collection from all Docker containers with label-based filtering",
      "Alertmanager: alert rules for high CPU (>80%), low disk space, container restart loops → Telegram bot notifications",
      "Added sample Go application with custom Prometheus metrics (request_count, response_latency_seconds) for testing the full pipeline",
      "Wrote README with setup instructions and architecture diagram",
    ],
    learned: "Full observability pipeline: metrics collection → visualization → alerting. PromQL basics, Grafana dashboard design, log aggregation patterns. Key insight: monitoring isn't just dashboards — it's about defining what 'healthy' means for your system.",
    techStack: [
      "Docker Compose",
      "Prometheus",
      "Grafana",
      "Loki",
      "Alertmanager",
      "Go",
    ],
    category: "Monitoring",
    imgPath: "",
    ghLink: "",
    demoLink: "",
  },
  {
    id: "ai-platform-devops",
    title: "ML Inference Platform — DevOps & Infrastructure",
    description:
      "Infrastructure and DevOps for a production ML platform with multi-provider inference routing, RAG search, and streaming APIs. Private commercial project — owned the full delivery and reliability pipeline.",
    role: [
      "Built CI/CD in GitHub Actions: test → lint → typecheck → build → native compile → format check (fail-fast, ~3 min)",
      "Configured multi-stage build pipeline: frontend → backend → native modules → code signing → packaging",
      "Set up secrets management: credential isolation per service, OAuth token refresh with TTL caching",
      "Implemented infrastructure monitoring: service liveness watchdog, per-provider latency tracking (TTFT), connection health metrics with alerting",
      "Configured search index — injection-safe query builder, automated data archival, bounded storage policies",
      "Hardened security: CSP policies, input validation on all API boundaries, SSRF protection, per-process capability isolation",
      "Built automated security audit pipeline with cross-verification — reduced false positive rate from 36% to under 5% over 4 iterations",
      "Maintained 900+ test suite with per-module coverage thresholds and regression gates",
    ],
    learned: "ML infrastructure has unique challenges: streaming responses, multi-provider failover, native OS integration, and credential lifecycle management. Key insight — reliability isn't about zero failures, it's about graceful degradation and fast recovery.",
    techStack: [
      "GitHub Actions",
      "Rust",
      "SQLite / FTS5",
      "WebSocket / SSE",
      "Shell / Scripting",
      "Native Build",
    ],
    category: "AI/MLOps",
    imgPath: "",
    ghLink: "",
    demoLink: "",
  },
  {
    id: "smartbee-portfolio",
    title: "SmartBee Portfolio",
    description:
      "This portfolio itself — built and deployed using the same DevOps practices I apply to infrastructure projects. Full GitOps workflow: code in GitHub, CI/CD pipeline, automated deployment. Because a DevOps engineer's portfolio should be a DevOps project.",
    role: [
      "Designed and built the site: React + Vite, responsive Liquid Glass design, i18n (EN/UA)",
      "Set up GitHub repository with branch protection rules and PR-based workflow",
      "Created GitHub Actions CI/CD: lint → build → deploy on merge to main",
      "Infrastructure as Code: deployment configuration managed in Git",
      "PDF resume generation with @react-pdf/renderer (build-time, not client-side)",
      "Interactive terminal resume — because engineers read terminals, not PDFs",
      "Monitoring: uptime checks, performance budgets, Lighthouse CI",
    ],
    learned: "End-to-end project ownership: from design to deployment to monitoring. Applying DevOps culture to everything — even a personal website deserves proper CI/CD and observability.",
    techStack: [
      "React",
      "Vite",
      "GitHub Actions",
      "Git",
      "Node.js",
      "i18n",
    ],
    category: "Platform",
    imgPath: "",
    ghLink: "https://github.com/meisnastia/hiveops",
    demoLink: "https://smartbee.me",
  },
];

export const PROJECT_CATEGORIES = ["All", "Cloud", "Monitoring", "AI/MLOps", "Platform"];
